### ISSUE TITLE
Communicating between apps

### ISSUE THREAD

**Issue by Muhammat97** [MrFrankel/share-loader#21]
Sorry, in your blog, you mention the event bus for communicating between apps. Could you please provide an example? I have tried a number of tutorials about that, but it didn't work. Thank you

**Comment by MrFrankel** [comment]
@Muhammat97 , sorry for the late reply, i've been away. ill try write an example here soon.

**Comment by RobM-ADP** [comment]
You can communicate via apps with a just an ordinary service:

In shell app.module:
```
providers: [
   {provide: 'COMMUNICATION_SERVICE', useClass: SomeService}
]
```
Then in the child apps, you can inject that:
```
export class SomeComponent {
   constructor(@Inject('COMMUNICATION_SERVICE') private commService: any) {
      this.commService.doSomething('data from child');
   }
}
```
The trick is injection token needs to be something that is accessible in both apps. You could use a simple string or the preferred approach would be to have real `InjectionToken` objects that themselves are from a shared library that is excluded from the children. You could also have an interface in the shared library so that you don't have to use `any` as the type when you inject it.

**Comment by alexej-strelzow** [comment]
@RobM-ADP  just gave the answer away ;-)

You can write you own Angular library (e.g. @app/shared) and import it in shell + children (via package.json) AND provide @app/shared in the webpack.config from your shell (and importing it in webpack.config from child-app - just like angular-lib) in order to have an application wide singleton (e.g. session-service or private event-bus) ;-)

See: https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5

**Comment by alexej-strelzow** [comment]
@Muhammat97 you can find an example of a private shared event-bus (app-wide singleton) here: https://github.com/BAWAG-PSK/wrd-bawag-mfa

**Comment by Muhammat97** [comment]
thank you all for the responses
